### ISSUE TITLE
JSON Adapter does not work with a folder

### ISSUE THREAD

**Issue by rothsandro** [cyon/vue-translation-manager#2]
The JSON adapter does not work if a folder, instead of a single file, is provided.

**Configuration**
vue-translation-manager@1.0.3 is locally installed

```
module.exports = {
  srcPath: path.join(__dirname, 'src/'),
  adapter: new JSONAdapter({ 
    path: path.join(__dirname, 'src/translations/')
  }),
  languages: ['de']
};
```

**Expected**
The JSON adapter should use the file `src/translations/de.json`.

**Current**
The following error is thrown:

(node:34295) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/some/path/src/translations/Users/some/path/src/translations/de.json'
(node:34295) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:34295) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by MaxGfeller** [comment]
There was another error in joining paths. Should be solved in `1.0.4`. Thanks for the report!
