### ISSUE TITLE
Pug template support

### ISSUE THREAD

**Issue by andron58** [cyon/vue-translation-manager#32]
Hi, is vue-translation-manager support pug-templates? When when i write _vue-translation-manager translate_ in console, I instantly get: _All components translated_ but transaltions files are empty

**Comment by evgenibir** [comment]
> Hi, is vue-translation-manager support pug-templates? When when i write _vue-translation-manager translate_ in console, I instantly get: _All components translated_ but transaltions files are empty

Hi @andron58! How you fixed it?
