### ISSUE TITLE
Add support for message parameters

### ISSUE THREAD

**Issue by MaxGfeller** [cyon/vue-translation-manager#4]
Both [vue-i18n](https://kazupon.github.io/vue-i18n/guide/formatting.html#named-formatting) and [vuex-i18n](https://www.npmjs.com/package/vuex-i18n) support passing dynamic parameters to messages. Example:

```vue
<h1>{{ $t('hello.title', { name: 'Max' }) }}</h1>
```

```json
{
  "hello": {
    "title": "Hallo, {name}"
  }
}
```

The vue-translation-manager should also be able to support those kinds of messages. The following should be detected and in the interactive prompt, the user should be instructed to insert those parameters.

```
<span>Hallo {{ name }}</span>
```

**Comment by marlass** [comment]
I would like to help you with that. Do you have some requirements about how it should be done or do I have freedom with the implementation?

**Comment by marlass** [comment]
Just to be sure. In the example you provided the final name won't be provided by user, but it will point to the same variable that was used before transformation.

Should that be result of the code?
`<h1>{{ $t('hello.title', { name }) }}</h1>`

**Comment by MaxGfeller** [comment]
That sounds great @marlass! This is exactly right, that's how it should be transformed.

I don't have any requirements but please make sure there is a test case for it and that your code follows the [Standard coding style](https://standardjs.com/).

**Comment by marlass** [comment]
I edited a comment above. Added some more advanced example. Could you take a look one more time?

**Comment by MaxGfeller** [comment]
Aight, that sounds very reasonable. Although i wouldn't make it result in an error if not all the parameters are specified. Theoretically those could be added only later too.
