### ISSUE TITLE
Incorrect parsing of attributes

### ISSUE THREAD

**Issue by aschempp** [cyon/vue-translation-manager#6]
Parsing attributes apparently does not stop if the next attribute starts with `@`.

Example:
```
<button type="button" title="My Title" @click="myAction">
```

The resulting key and label contains everything from title and action, e.g. `My Title" @click="myAction`

**Comment by aschempp** [comment]
This seems to be happening on any attribute if it's not the last one.

**Comment by MaxGfeller** [comment]
There was an error in the regex used for attributes. Should be fixed in `1.0.7`.
